name: Draft New Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release Alpha
        id: create-release-alpha
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: vv.8.3-alpha
          release_name: v0.8.3-alpha
          draft: false

      - name: Create Release Beta
        id: create-release-beta
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.8.3-beta
          release_name: v0.8.3-beta
          draft: true
